### PR TITLE
translate into Simplified Chinese

### PR DESCRIPTION
**Pull request by Chalkim**

### CODE REVIEW

**Comment by varlesh** [comment]
You can update translate? I'm only now add **Lock Scree**n button

**Comment by varlesh** [comment]
please open new PR for solve conflicts

**Comment by Chalkim** [comment]
OK, that's fine. I will keep up translating if new features come out.

**Comment by varlesh** [comment]
i'm add your translate, big thx. 
Now need translate `Lock Screen`

**Comment by Chalkim** [comment]
OK, I'm still learning about how to use git. Far from skilled enough. Sorry for that.

**Comment by varlesh** [comment]
No problem.
I can finish))
锁屏 right?

**Comment by varlesh** [comment]
from Google translate

**Comment by Chalkim** [comment]
OK, that's ok

**Comment by varlesh** [comment]
all done

**Pull request closed without merging**
